Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
band = nuda.matter.setupMicroBand( models, matter='NM' )
band.print_outputs( )
------------------

----- stdout -----

Band in NM
model ->  2013-QMC-NM
model ->  2016-QMC-NM
model ->  2016-MBPT-AM
model ->  2013-QMC-NM
model ->  2016-QMC-NM
model ->  2016-MBPT-AM
model ->  2013-QMC-NM
model ->  2016-QMC-NM
model ->  2016-MBPT-AM
- Print output:
   models : ['2013-QMC-NM', '2016-QMC-NM', '2016-MBPT-AM']
   den_min: 0.04
   den_max: 0.16
   den : [0.04  0.052 0.064 0.076 0.088 0.1   0.112 0.124 0.136 0.148 0.16 ]
   kfn : [1.06 1.15 1.24 1.31 1.38 1.44 1.49 1.54 1.59 1.64 1.68]
------------------

[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[11][39m[32m, line 2[39m
[32m      1[39m band = nuda.matter.setupMicroBand( models, matter=[33m'[39m[33mNM[39m[33m'[39m )
[32m----> [39m[32m2[39m [43mband[49m[43m.[49m[43mprint_outputs[49m[43m([49m[43m [49m[43m)[49m

[36mFile [39m[32m~/work/nucleardatapy/nucleardatapy/version-0.2/nucleardatapy/matter/setup_micro_band.py:218[39m, in [36msetupMicroBand.print_outputs[39m[34m(self)[39m
[32m    216[39m [38;5;28mprint[39m([33m"[39m[33m   den :[39m[33m"[39m,np.round([38;5;28mself[39m.den,[32m3[39m))
[32m    217[39m [38;5;28mprint[39m([33m"[39m[33m   kfn :[39m[33m"[39m,np.round([38;5;28mself[39m.kfn,[32m2[39m))
[32m--> [39m[32m218[39m [38;5;28mprint[39m([33m"[39m[33m   e2a :[39m[33m"[39m,np.round([38;5;28;43mself[39;49m[43m.[49m[43me2a[49m,[32m2[39m))
[32m    219[39m [38;5;28mprint[39m([33m"[39m[33m   std :[39m[33m"[39m,np.round([38;5;28mself[39m.e2a_std,[32m3[39m))
[32m    220[39m [38;5;66;03m#if self.sm_den is not None: print(f"   sm_den: {np.round(self.sm_den,3)} in {self.den_unit}")[39;00m
[32m    221[39m [38;5;66;03m#[39;00m

[31mAttributeError[39m: 'setupMicroBand' object has no attribute 'e2a'

